version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - "./mysql/volume:/var/lib/mysql"
      - "./mysql/init-dev:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=dev
  server:
    build:
      context: ./server
    restart: always
    volumes:
      - /server/node_modules
      - ./server:/server
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=dev
      - DB_PASSWORD=dev
      - DB_DATABASE=dev
    ports:
      - 4000:4000
    depends_on:
      - mysql
  client:
    build:
      context: ./client
    restart: always
    volumes:
      - /client/node_modules
      - ./client:/client
    ports:
      - 3000:3000